#!/bin/bash

# Script for LAN recon
# By zw9seq

# Check dependencies
for cmd in arp-scan masscan gowitness macchanger; do
    if ! command -v $cmd &>/dev/null; then
        echo "[-] $cmd not found, please install it."
        exit 1
    fi
done

# Ask for the target
read -p "Specify the name of the target: " target
while [ -z "$target" ]; do
    echo -e "\nPlease enter the name of the target.\n"
    sleep 1
    read -p "Specify the name of the target: " target
done

# Variables
dir="$HOME/Lab/${target}"
hosts="${dir}/hosts.txt"
hostsIps="/tmp/ips.txt"
ports="${dir}/ports.txt"
scanPorts="/tmp/scanPorts.txt"
netInt=$(ip route | grep '^default' | awk '{print $5}')

# Look if the directory already exists
if ! [ -d "${dir}" ]
then
    mkdir "${dir}"
fi

# Ask for the MAC change
while true; do
    read -p "Do you want to change your MAC address? [y/n] " res
    if [[ "$res" == "y" || "$res" == "n" ]]; then
        break
    fi
    echo -e "\nAnswer y or n.\n"
    sleep 1
done

# Change the MAC
if [[ "$res" == "y" ]]; then
    echo -e "\nChanging MAC\n"
    sudo ifconfig "$netInt" down
    sleep 1
    sudo macchanger -a "$netInt" &>/dev/null
    sleep 1
    sudo ifconfig "$netInt" up
    echo -e "MAC changed to: $(macchanger -s "$netInt" | grep "Current MAC" | cut -d " " -f 5)\n"
fi

# Get the active hosts
echo -e "Scanning the net...\n"
touch "${hosts}"
sudo arp-scan -I "$netInt" -l -r 5 -i 7 -x -q >"${hosts}"
echo -e "Scan finished.\n"

# Scan the hosts's ports
echo -e "Starting port scan...\n"
cut -f 1 "${hosts}" > "${hostsIps}"
sudo masscan -p80,22,21,25,53,443,3306,139,445,3389,389,161,554,1433,1521,5432,8080 --rate=1000 --source-port=53 -iL "${hostsIps}" -oG "${ports}" &>/dev/null
rm "${hostsIps}"
echo -e "Port scan finished.\n"

# Take screenshots of the hosts's webs
echo -e "Getting the webs from the hosts...\n"
grep "Ports: 80" "${ports}" | awk '{print $4}' > "${scanPorts}"
grep "Ports: 443" "${ports}" | awk '{print $4}' >> "${scanPorts}"
gowitness scan file -f "${scanPorts}" --screenshot-path "${dir}/screenshots" &>/dev/null
echo -e "Web recon finished.\n"

# Remove temp files
echo -e "Removing temporary files..."
rm "${scanPorts}"

echo -e "\nNetrecon finished."
exit 0
